# Build stage
FROM oven/bun:latest as build

WORKDIR /app

# Accept build arguments for environment variables
ARG VITE_NODE_ENV=production
ARG VITE_PORT=8808
ARG VITE_APP_VERSION=1.0.0
ARG VITE_DEBUG=false
ARG VITE_API_URL
ARG VITE_AUTH_URL
ARG VITE_API_BASE_URL
ARG VITE_STORAGE_URL
ARG VITE_APP_SECRET_KEY
ARG VITE_APP_STORAGE_SECRET_KEY
ARG VITE_APP_STORAGE_API_KEY
ARG VITE_TOMTOM_API_KEY
ARG VITE_TOMTOM_STYLE_DARK
ARG VITE_TOMTOM_STYLE_LIGHT
ARG VITE_SOCKET_URL
ARG VITE_DOCS_URL
ARG VITE_DEVELOPER_URL
ARG VITE_API_AI_URL
ARG VITE_GEMINI_API_KEY
ARG ENABLE_TANSTACK_ROUTE_GENERATION=true

# Set environment variables for the build
ENV VITE_NODE_ENV=${VITE_NODE_ENV}
ENV VITE_PORT=${VITE_PORT}
ENV VITE_APP_VERSION=${VITE_APP_VERSION}
ENV VITE_DEBUG=${VITE_DEBUG}
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_AUTH_URL=${VITE_AUTH_URL}
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_STORAGE_URL=${VITE_STORAGE_URL}
ENV VITE_APP_SECRET_KEY=${VITE_APP_SECRET_KEY}
ENV VITE_APP_STORAGE_SECRET_KEY=${VITE_APP_STORAGE_SECRET_KEY}
ENV VITE_APP_STORAGE_API_KEY=${VITE_APP_STORAGE_API_KEY}
ENV VITE_TOMTOM_API_KEY=${VITE_TOMTOM_API_KEY}
ENV VITE_TOMTOM_STYLE_DARK=${VITE_TOMTOM_STYLE_DARK}
ENV VITE_TOMTOM_STYLE_LIGHT=${VITE_TOMTOM_STYLE_LIGHT}
ENV VITE_SOCKET_URL=${VITE_SOCKET_URL}
ENV VITE_DOCS_URL=${VITE_DOCS_URL}
ENV VITE_DEVELOPER_URL=${VITE_DEVELOPER_URL}
ENV VITE_API_AI_URL=${VITE_API_AI_URL}
ENV VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
ENV ENABLE_TANSTACK_ROUTE_GENERATION=${ENABLE_TANSTACK_ROUTE_GENERATION}

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Set NODE_ENV for the build
ENV NODE_ENV=production

# Build the application with increased memory limit if needed
RUN bun run build

# Production stage
FROM oven/bun:latest

WORKDIR /app

# Install a simple http server to serve static content
RUN bun install --global serve

# Copy build artifacts from build stage
COPY --from=build /app/dist /app/dist

# Set environment variables
ENV NODE_ENV=production
ENV PORT=8808

# Expose the port
EXPOSE 8808

# Command to run the application
CMD ["serve", "-s", "dist", "-l", "8808"]