/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AppAppRouteImport } from './routes/app/_app'
import { Route as AppAppIndexRouteImport } from './routes/app/_app/index'
import { Route as AppAppTestRouteImport } from './routes/app/_app/test'
import { Route as AuthAuthVerifyEmailRouteImport } from './routes/_auth/auth/verify-email'
import { Route as AuthAuthPasswordResetRouteImport } from './routes/_auth/auth/password-reset'
import { Route as AuthAuthJoinRouteImport } from './routes/_auth/auth/join'
import { Route as AppAppManagerManagerRouteImport } from './routes/app/_app/manager/_manager'
import { Route as AppAppHrHrRouteImport } from './routes/app/_app/hr/_hr'
import { Route as AppAppDevelopmentDevelopmentRouteImport } from './routes/app/_app/development/_development'
import { Route as AppAppAdminAdminRouteImport } from './routes/app/_app/admin/_admin'
import { Route as AppAppAccountAccountRouteImport } from './routes/app/_app/account/_account'
import { Route as AppAppManagerManagerTrackingIndexRouteImport } from './routes/app/_app/manager/_manager/tracking/index'
import { Route as AppAppAdminAdminServersDbIndexRouteImport } from './routes/app/_app/admin/_admin/servers-db/index'
import { Route as AppAppAdminAdminSettingsSettingsRouteImport } from './routes/app/_app/admin/_admin/settings/_settings'
import { Route as AppAppAdminAdminConfigurationConfigurationRouteImport } from './routes/app/_app/admin/_admin/configuration/_configuration'
import { Route as AppAppAccountAccountProfileProfileRouteImport } from './routes/app/_app/account/_account/profile/_profile'
import { Route as AppAppAdminAdminConfigurationConfigurationIndexRouteImport } from './routes/app/_app/admin/_admin/configuration/_configuration/index'

const AppRouteImport = createFileRoute('/app')()
const AppAppManagerRouteImport = createFileRoute('/app/_app/manager')()
const AppAppHrRouteImport = createFileRoute('/app/_app/hr')()
const AppAppDevelopmentRouteImport = createFileRoute('/app/_app/development')()
const AppAppAdminRouteImport = createFileRoute('/app/_app/admin')()
const AppAppAccountRouteImport = createFileRoute('/app/_app/account')()
const AppAppAnnouncementsLazyRouteImport = createFileRoute(
  '/app/_app/announcements',
)()
const AppAppChatsIndexLazyRouteImport = createFileRoute('/app/_app/chats/')()
const AppAppAdminAdminSettingsRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings',
)()
const AppAppAdminAdminConfigurationRouteImport = createFileRoute(
  '/app/_app/admin/_admin/configuration',
)()
const AppAppAccountAccountProfileRouteImport = createFileRoute(
  '/app/_app/account/_account/profile',
)()
const AppAppHrHrNotesLazyRouteImport = createFileRoute(
  '/app/_app/hr/_hr/notes',
)()
const AppAppHrHrManageRequestsLazyRouteImport = createFileRoute(
  '/app/_app/hr/_hr/manage-requests',
)()
const AppAppHrHrLeaveManagementLazyRouteImport = createFileRoute(
  '/app/_app/hr/_hr/leave-management',
)()
const AppAppHrHrEmployeesLazyRouteImport = createFileRoute(
  '/app/_app/hr/_hr/employees',
)()
const AppAppHrHrCalendarLazyRouteImport = createFileRoute(
  '/app/_app/hr/_hr/calendar',
)()
const AppAppHrHrAttendanceLazyRouteImport = createFileRoute(
  '/app/_app/hr/_hr/attendance',
)()
const AppAppDevelopmentDevelopmentToolkitLazyRouteImport = createFileRoute(
  '/app/_app/development/_development/toolkit',
)()
const AppAppDevelopmentDevelopmentTicketsLazyRouteImport = createFileRoute(
  '/app/_app/development/_development/tickets',
)()
const AppAppDevelopmentDevelopmentTerminalLazyRouteImport = createFileRoute(
  '/app/_app/development/_development/terminal',
)()
const AppAppDevelopmentDevelopmentRepositoriesLazyRouteImport = createFileRoute(
  '/app/_app/development/_development/repositories',
)()
const AppAppAdminAdminDocsLazyLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/docs',
)()
const AppAppAdminAdminBackupLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/backup',
)()
const AppAppAdminAdminApiKeysLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/api-keys',
)()
const AppAppAdminAdminActivityMonitorLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/activity-monitor',
)()
const AppAppAccountAccountRequestsLazyRouteImport = createFileRoute(
  '/app/_app/account/_account/requests',
)()
const AppAppAccountAccountProjectsLazyRouteImport = createFileRoute(
  '/app/_app/account/_account/projects',
)()
const AppAppAccountAccountDriveLazyRouteImport = createFileRoute(
  '/app/_app/account/_account/drive',
)()
const AppAppAdminAdminSettingsSettingsIndexLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/',
)()
const AppAppAccountAccountProfileProfileIndexLazyRouteImport = createFileRoute(
  '/app/_app/account/_account/profile/_profile/',
)()
const AppAppAdminAdminSettingsSettingsUploadLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/upload',
)()
const AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRouteImport =
  createFileRoute(
    '/app/_app/admin/_admin/settings/_settings/translations-localization',
  )()
const AppAppAdminAdminSettingsSettingsSmtpLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/smtp',
)()
const AppAppAdminAdminSettingsSettingsSecurityLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/security',
)()
const AppAppAdminAdminSettingsSettingsRoleManagementLazyRouteImport =
  createFileRoute('/app/_app/admin/_admin/settings/_settings/role-management')()
const AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRouteImport =
  createFileRoute(
    '/app/_app/admin/_admin/settings/_settings/payments-billing',
  )()
const AppAppAdminAdminSettingsSettingsNotificationsLazyRouteImport =
  createFileRoute('/app/_app/admin/_admin/settings/_settings/notifications')()
const AppAppAdminAdminSettingsSettingsMobileAppsLazyRouteImport =
  createFileRoute('/app/_app/admin/_admin/settings/_settings/mobile-apps')()
const AppAppAdminAdminSettingsSettingsMetaDataLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/meta-data',
)()
const AppAppAdminAdminSettingsSettingsLogSettingsLazyRouteImport =
  createFileRoute('/app/_app/admin/_admin/settings/_settings/log-settings')()
const AppAppAdminAdminSettingsSettingsLicenseLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/license',
)()
const AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRouteImport =
  createFileRoute(
    '/app/_app/admin/_admin/settings/_settings/languages-region',
  )()
const AppAppAdminAdminSettingsSettingsHelpSupportLazyRouteImport =
  createFileRoute('/app/_app/admin/_admin/settings/_settings/help-support')()
const AppAppAdminAdminSettingsSettingsDriveLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/drive',
)()
const AppAppAdminAdminSettingsSettingsCompaniesLazyRouteImport =
  createFileRoute('/app/_app/admin/_admin/settings/_settings/companies')()
const AppAppAdminAdminSettingsSettingsBackupLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/backup',
)()
const AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRouteImport =
  createFileRoute(
    '/app/_app/admin/_admin/settings/_settings/appearance-theme',
  )()
const AppAppAdminAdminSettingsSettingsApiKeysLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/api-keys',
)()
const AppAppAdminAdminSettingsSettingsAmcLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/amc',
)()
const AppAppAdminAdminSettingsSettingsAboutLazyRouteImport = createFileRoute(
  '/app/_app/admin/_admin/settings/_settings/about',
)()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AppRoute,
} as any)
const AppAppManagerRoute = AppAppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppHrRoute = AppAppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppDevelopmentRoute = AppAppDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAdminRoute = AppAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAccountRoute = AppAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAnnouncementsLazyRoute = AppAppAnnouncementsLazyRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppAppRoute,
} as any).lazy(() =>
  import('./routes/app/_app/announcements.lazy').then((d) => d.Route),
)
const AppAppTestRoute = AppAppTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppAppRoute,
} as any)
const AuthAuthVerifyEmailRoute = AuthAuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthPasswordResetRoute = AuthAuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthJoinRoute = AuthAuthJoinRouteImport.update({
  id: '/auth/join',
  path: '/auth/join',
  getParentRoute: () => AuthRoute,
} as any)
const AppAppChatsIndexLazyRoute = AppAppChatsIndexLazyRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppAppRoute,
} as any).lazy(() =>
  import('./routes/app/_app/chats/index.lazy').then((d) => d.Route),
)
const AppAppManagerManagerRoute = AppAppManagerManagerRouteImport.update({
  id: '/_manager',
  getParentRoute: () => AppAppManagerRoute,
} as any)
const AppAppHrHrRoute = AppAppHrHrRouteImport.update({
  id: '/_hr',
  getParentRoute: () => AppAppHrRoute,
} as any)
const AppAppDevelopmentDevelopmentRoute =
  AppAppDevelopmentDevelopmentRouteImport.update({
    id: '/_development',
    getParentRoute: () => AppAppDevelopmentRoute,
  } as any)
const AppAppAdminAdminRoute = AppAppAdminAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppAppAdminRoute,
} as any)
const AppAppAccountAccountRoute = AppAppAccountAccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => AppAppAccountRoute,
} as any)
const AppAppAdminAdminSettingsRoute =
  AppAppAdminAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAppAdminAdminRoute,
  } as any)
const AppAppAdminAdminConfigurationRoute =
  AppAppAdminAdminConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AppAppAdminAdminRoute,
  } as any)
const AppAppAccountAccountProfileRoute =
  AppAppAccountAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AppAppAccountAccountRoute,
  } as any)
const AppAppHrHrNotesLazyRoute = AppAppHrHrNotesLazyRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppAppHrHrRoute,
} as any).lazy(() =>
  import('./routes/app/_app/hr/_hr/notes.lazy').then((d) => d.Route),
)
const AppAppHrHrManageRequestsLazyRoute =
  AppAppHrHrManageRequestsLazyRouteImport.update({
    id: '/manage-requests',
    path: '/manage-requests',
    getParentRoute: () => AppAppHrHrRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/hr/_hr/manage-requests.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppHrHrLeaveManagementLazyRoute =
  AppAppHrHrLeaveManagementLazyRouteImport.update({
    id: '/leave-management',
    path: '/leave-management',
    getParentRoute: () => AppAppHrHrRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/hr/_hr/leave-management.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppHrHrEmployeesLazyRoute = AppAppHrHrEmployeesLazyRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppAppHrHrRoute,
} as any).lazy(() =>
  import('./routes/app/_app/hr/_hr/employees.lazy').then((d) => d.Route),
)
const AppAppHrHrCalendarLazyRoute = AppAppHrHrCalendarLazyRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppAppHrHrRoute,
} as any).lazy(() =>
  import('./routes/app/_app/hr/_hr/calendar.lazy').then((d) => d.Route),
)
const AppAppHrHrAttendanceLazyRoute =
  AppAppHrHrAttendanceLazyRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AppAppHrHrRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/hr/_hr/attendance.lazy').then((d) => d.Route),
  )
const AppAppDevelopmentDevelopmentToolkitLazyRoute =
  AppAppDevelopmentDevelopmentToolkitLazyRouteImport.update({
    id: '/toolkit',
    path: '/toolkit',
    getParentRoute: () => AppAppDevelopmentDevelopmentRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/development/_development/toolkit.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppDevelopmentDevelopmentTicketsLazyRoute =
  AppAppDevelopmentDevelopmentTicketsLazyRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AppAppDevelopmentDevelopmentRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/development/_development/tickets.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppDevelopmentDevelopmentTerminalLazyRoute =
  AppAppDevelopmentDevelopmentTerminalLazyRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => AppAppDevelopmentDevelopmentRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/development/_development/terminal.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppDevelopmentDevelopmentRepositoriesLazyRoute =
  AppAppDevelopmentDevelopmentRepositoriesLazyRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => AppAppDevelopmentDevelopmentRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/development/_development/repositories.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAdminAdminDocsLazyLazyRoute =
  AppAppAdminAdminDocsLazyLazyRouteImport.update({
    id: '/docs',
    path: '/docs',
    getParentRoute: () => AppAppAdminAdminRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/docs.lazy.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAdminAdminBackupLazyRoute =
  AppAppAdminAdminBackupLazyRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AppAppAdminAdminRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/backup.lazy').then((d) => d.Route),
  )
const AppAppAdminAdminApiKeysLazyRoute =
  AppAppAdminAdminApiKeysLazyRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AppAppAdminAdminRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/api-keys.lazy').then((d) => d.Route),
  )
const AppAppAdminAdminActivityMonitorLazyRoute =
  AppAppAdminAdminActivityMonitorLazyRouteImport.update({
    id: '/activity-monitor',
    path: '/activity-monitor',
    getParentRoute: () => AppAppAdminAdminRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/activity-monitor.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAccountAccountRequestsLazyRoute =
  AppAppAccountAccountRequestsLazyRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AppAppAccountAccountRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/account/_account/requests.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAccountAccountProjectsLazyRoute =
  AppAppAccountAccountProjectsLazyRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AppAppAccountAccountRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/account/_account/projects.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAccountAccountDriveLazyRoute =
  AppAppAccountAccountDriveLazyRouteImport.update({
    id: '/drive',
    path: '/drive',
    getParentRoute: () => AppAppAccountAccountRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/account/_account/drive.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppManagerManagerTrackingIndexRoute =
  AppAppManagerManagerTrackingIndexRouteImport.update({
    id: '/tracking/',
    path: '/tracking/',
    getParentRoute: () => AppAppManagerManagerRoute,
  } as any)
const AppAppAdminAdminServersDbIndexRoute =
  AppAppAdminAdminServersDbIndexRouteImport.update({
    id: '/servers-db/',
    path: '/servers-db/',
    getParentRoute: () => AppAppAdminAdminRoute,
  } as any)
const AppAppAdminAdminSettingsSettingsRoute =
  AppAppAdminAdminSettingsSettingsRouteImport.update({
    id: '/_settings',
    getParentRoute: () => AppAppAdminAdminSettingsRoute,
  } as any)
const AppAppAdminAdminConfigurationConfigurationRoute =
  AppAppAdminAdminConfigurationConfigurationRouteImport.update({
    id: '/_configuration',
    getParentRoute: () => AppAppAdminAdminConfigurationRoute,
  } as any)
const AppAppAccountAccountProfileProfileRoute =
  AppAppAccountAccountProfileProfileRouteImport.update({
    id: '/_profile',
    getParentRoute: () => AppAppAccountAccountProfileRoute,
  } as any)
const AppAppAdminAdminSettingsSettingsIndexLazyRoute =
  AppAppAdminAdminSettingsSettingsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/settings/_settings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAccountAccountProfileProfileIndexLazyRoute =
  AppAppAccountAccountProfileProfileIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAppAccountAccountProfileProfileRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/account/_account/profile/_profile/index.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminConfigurationConfigurationIndexRoute =
  AppAppAdminAdminConfigurationConfigurationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAppAdminAdminConfigurationConfigurationRoute,
  } as any)
const AppAppAdminAdminSettingsSettingsUploadLazyRoute =
  AppAppAdminAdminSettingsSettingsUploadLazyRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/upload.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute =
  AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRouteImport.update(
    {
      id: '/translations-localization',
      path: '/translations-localization',
      getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
    } as any,
  ).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/translations-localization.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsSmtpLazyRoute =
  AppAppAdminAdminSettingsSettingsSmtpLazyRouteImport.update({
    id: '/smtp',
    path: '/smtp',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/settings/_settings/smtp.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAdminAdminSettingsSettingsSecurityLazyRoute =
  AppAppAdminAdminSettingsSettingsSecurityLazyRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/security.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute =
  AppAppAdminAdminSettingsSettingsRoleManagementLazyRouteImport.update({
    id: '/role-management',
    path: '/role-management',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/role-management.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute =
  AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRouteImport.update({
    id: '/payments-billing',
    path: '/payments-billing',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/payments-billing.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsNotificationsLazyRoute =
  AppAppAdminAdminSettingsSettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/notifications.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute =
  AppAppAdminAdminSettingsSettingsMobileAppsLazyRouteImport.update({
    id: '/mobile-apps',
    path: '/mobile-apps',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/mobile-apps.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsMetaDataLazyRoute =
  AppAppAdminAdminSettingsSettingsMetaDataLazyRouteImport.update({
    id: '/meta-data',
    path: '/meta-data',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/meta-data.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute =
  AppAppAdminAdminSettingsSettingsLogSettingsLazyRouteImport.update({
    id: '/log-settings',
    path: '/log-settings',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/log-settings.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsLicenseLazyRoute =
  AppAppAdminAdminSettingsSettingsLicenseLazyRouteImport.update({
    id: '/license',
    path: '/license',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/license.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute =
  AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRouteImport.update({
    id: '/languages-region',
    path: '/languages-region',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/languages-region.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute =
  AppAppAdminAdminSettingsSettingsHelpSupportLazyRouteImport.update({
    id: '/help-support',
    path: '/help-support',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/help-support.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsDriveLazyRoute =
  AppAppAdminAdminSettingsSettingsDriveLazyRouteImport.update({
    id: '/drive',
    path: '/drive',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/settings/_settings/drive.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAdminAdminSettingsSettingsCompaniesLazyRoute =
  AppAppAdminAdminSettingsSettingsCompaniesLazyRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/companies.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsBackupLazyRoute =
  AppAppAdminAdminSettingsSettingsBackupLazyRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/backup.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute =
  AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRouteImport.update({
    id: '/appearance-theme',
    path: '/appearance-theme',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/appearance-theme.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsApiKeysLazyRoute =
  AppAppAdminAdminSettingsSettingsApiKeysLazyRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import(
      './routes/app/_app/admin/_admin/settings/_settings/api-keys.lazy'
    ).then((d) => d.Route),
  )
const AppAppAdminAdminSettingsSettingsAmcLazyRoute =
  AppAppAdminAdminSettingsSettingsAmcLazyRouteImport.update({
    id: '/amc',
    path: '/amc',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/settings/_settings/amc.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAppAdminAdminSettingsSettingsAboutLazyRoute =
  AppAppAdminAdminSettingsSettingsAboutLazyRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AppAppAdminAdminSettingsSettingsRoute,
  } as any).lazy(() =>
    import('./routes/app/_app/admin/_admin/settings/_settings/about.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/app': typeof AppAppRouteWithChildren
  '/': typeof AuthIndexRoute
  '/auth/join': typeof AuthAuthJoinRoute
  '/auth/password-reset': typeof AuthAuthPasswordResetRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/app/test': typeof AppAppTestRoute
  '/app/announcements': typeof AppAppAnnouncementsLazyRoute
  '/app/': typeof AppAppIndexRoute
  '/app/account': typeof AppAppAccountAccountRouteWithChildren
  '/app/admin': typeof AppAppAdminAdminRouteWithChildren
  '/app/development': typeof AppAppDevelopmentDevelopmentRouteWithChildren
  '/app/hr': typeof AppAppHrHrRouteWithChildren
  '/app/manager': typeof AppAppManagerManagerRouteWithChildren
  '/app/chats': typeof AppAppChatsIndexLazyRoute
  '/app/account/drive': typeof AppAppAccountAccountDriveLazyRoute
  '/app/account/projects': typeof AppAppAccountAccountProjectsLazyRoute
  '/app/account/requests': typeof AppAppAccountAccountRequestsLazyRoute
  '/app/admin/activity-monitor': typeof AppAppAdminAdminActivityMonitorLazyRoute
  '/app/admin/api-keys': typeof AppAppAdminAdminApiKeysLazyRoute
  '/app/admin/backup': typeof AppAppAdminAdminBackupLazyRoute
  '/app/admin/docs': typeof AppAppAdminAdminDocsLazyLazyRoute
  '/app/development/repositories': typeof AppAppDevelopmentDevelopmentRepositoriesLazyRoute
  '/app/development/terminal': typeof AppAppDevelopmentDevelopmentTerminalLazyRoute
  '/app/development/tickets': typeof AppAppDevelopmentDevelopmentTicketsLazyRoute
  '/app/development/toolkit': typeof AppAppDevelopmentDevelopmentToolkitLazyRoute
  '/app/hr/attendance': typeof AppAppHrHrAttendanceLazyRoute
  '/app/hr/calendar': typeof AppAppHrHrCalendarLazyRoute
  '/app/hr/employees': typeof AppAppHrHrEmployeesLazyRoute
  '/app/hr/leave-management': typeof AppAppHrHrLeaveManagementLazyRoute
  '/app/hr/manage-requests': typeof AppAppHrHrManageRequestsLazyRoute
  '/app/hr/notes': typeof AppAppHrHrNotesLazyRoute
  '/app/account/profile': typeof AppAppAccountAccountProfileProfileRouteWithChildren
  '/app/admin/configuration': typeof AppAppAdminAdminConfigurationConfigurationRouteWithChildren
  '/app/admin/settings': typeof AppAppAdminAdminSettingsSettingsRouteWithChildren
  '/app/admin/servers-db': typeof AppAppAdminAdminServersDbIndexRoute
  '/app/manager/tracking': typeof AppAppManagerManagerTrackingIndexRoute
  '/app/admin/settings/about': typeof AppAppAdminAdminSettingsSettingsAboutLazyRoute
  '/app/admin/settings/amc': typeof AppAppAdminAdminSettingsSettingsAmcLazyRoute
  '/app/admin/settings/api-keys': typeof AppAppAdminAdminSettingsSettingsApiKeysLazyRoute
  '/app/admin/settings/appearance-theme': typeof AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute
  '/app/admin/settings/backup': typeof AppAppAdminAdminSettingsSettingsBackupLazyRoute
  '/app/admin/settings/companies': typeof AppAppAdminAdminSettingsSettingsCompaniesLazyRoute
  '/app/admin/settings/drive': typeof AppAppAdminAdminSettingsSettingsDriveLazyRoute
  '/app/admin/settings/help-support': typeof AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute
  '/app/admin/settings/languages-region': typeof AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute
  '/app/admin/settings/license': typeof AppAppAdminAdminSettingsSettingsLicenseLazyRoute
  '/app/admin/settings/log-settings': typeof AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute
  '/app/admin/settings/meta-data': typeof AppAppAdminAdminSettingsSettingsMetaDataLazyRoute
  '/app/admin/settings/mobile-apps': typeof AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute
  '/app/admin/settings/notifications': typeof AppAppAdminAdminSettingsSettingsNotificationsLazyRoute
  '/app/admin/settings/payments-billing': typeof AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute
  '/app/admin/settings/role-management': typeof AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute
  '/app/admin/settings/security': typeof AppAppAdminAdminSettingsSettingsSecurityLazyRoute
  '/app/admin/settings/smtp': typeof AppAppAdminAdminSettingsSettingsSmtpLazyRoute
  '/app/admin/settings/translations-localization': typeof AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute
  '/app/admin/settings/upload': typeof AppAppAdminAdminSettingsSettingsUploadLazyRoute
  '/app/admin/configuration/': typeof AppAppAdminAdminConfigurationConfigurationIndexRoute
  '/app/account/profile/': typeof AppAppAccountAccountProfileProfileIndexLazyRoute
  '/app/admin/settings/': typeof AppAppAdminAdminSettingsSettingsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppAppIndexRoute
  '/': typeof AuthIndexRoute
  '/auth/join': typeof AuthAuthJoinRoute
  '/auth/password-reset': typeof AuthAuthPasswordResetRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/app/test': typeof AppAppTestRoute
  '/app/announcements': typeof AppAppAnnouncementsLazyRoute
  '/app/account': typeof AppAppAccountAccountRouteWithChildren
  '/app/admin': typeof AppAppAdminAdminRouteWithChildren
  '/app/development': typeof AppAppDevelopmentDevelopmentRouteWithChildren
  '/app/hr': typeof AppAppHrHrRouteWithChildren
  '/app/manager': typeof AppAppManagerManagerRouteWithChildren
  '/app/chats': typeof AppAppChatsIndexLazyRoute
  '/app/account/drive': typeof AppAppAccountAccountDriveLazyRoute
  '/app/account/projects': typeof AppAppAccountAccountProjectsLazyRoute
  '/app/account/requests': typeof AppAppAccountAccountRequestsLazyRoute
  '/app/admin/activity-monitor': typeof AppAppAdminAdminActivityMonitorLazyRoute
  '/app/admin/api-keys': typeof AppAppAdminAdminApiKeysLazyRoute
  '/app/admin/backup': typeof AppAppAdminAdminBackupLazyRoute
  '/app/admin/docs': typeof AppAppAdminAdminDocsLazyLazyRoute
  '/app/development/repositories': typeof AppAppDevelopmentDevelopmentRepositoriesLazyRoute
  '/app/development/terminal': typeof AppAppDevelopmentDevelopmentTerminalLazyRoute
  '/app/development/tickets': typeof AppAppDevelopmentDevelopmentTicketsLazyRoute
  '/app/development/toolkit': typeof AppAppDevelopmentDevelopmentToolkitLazyRoute
  '/app/hr/attendance': typeof AppAppHrHrAttendanceLazyRoute
  '/app/hr/calendar': typeof AppAppHrHrCalendarLazyRoute
  '/app/hr/employees': typeof AppAppHrHrEmployeesLazyRoute
  '/app/hr/leave-management': typeof AppAppHrHrLeaveManagementLazyRoute
  '/app/hr/manage-requests': typeof AppAppHrHrManageRequestsLazyRoute
  '/app/hr/notes': typeof AppAppHrHrNotesLazyRoute
  '/app/account/profile': typeof AppAppAccountAccountProfileProfileIndexLazyRoute
  '/app/admin/configuration': typeof AppAppAdminAdminConfigurationConfigurationIndexRoute
  '/app/admin/settings': typeof AppAppAdminAdminSettingsSettingsIndexLazyRoute
  '/app/admin/servers-db': typeof AppAppAdminAdminServersDbIndexRoute
  '/app/manager/tracking': typeof AppAppManagerManagerTrackingIndexRoute
  '/app/admin/settings/about': typeof AppAppAdminAdminSettingsSettingsAboutLazyRoute
  '/app/admin/settings/amc': typeof AppAppAdminAdminSettingsSettingsAmcLazyRoute
  '/app/admin/settings/api-keys': typeof AppAppAdminAdminSettingsSettingsApiKeysLazyRoute
  '/app/admin/settings/appearance-theme': typeof AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute
  '/app/admin/settings/backup': typeof AppAppAdminAdminSettingsSettingsBackupLazyRoute
  '/app/admin/settings/companies': typeof AppAppAdminAdminSettingsSettingsCompaniesLazyRoute
  '/app/admin/settings/drive': typeof AppAppAdminAdminSettingsSettingsDriveLazyRoute
  '/app/admin/settings/help-support': typeof AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute
  '/app/admin/settings/languages-region': typeof AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute
  '/app/admin/settings/license': typeof AppAppAdminAdminSettingsSettingsLicenseLazyRoute
  '/app/admin/settings/log-settings': typeof AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute
  '/app/admin/settings/meta-data': typeof AppAppAdminAdminSettingsSettingsMetaDataLazyRoute
  '/app/admin/settings/mobile-apps': typeof AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute
  '/app/admin/settings/notifications': typeof AppAppAdminAdminSettingsSettingsNotificationsLazyRoute
  '/app/admin/settings/payments-billing': typeof AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute
  '/app/admin/settings/role-management': typeof AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute
  '/app/admin/settings/security': typeof AppAppAdminAdminSettingsSettingsSecurityLazyRoute
  '/app/admin/settings/smtp': typeof AppAppAdminAdminSettingsSettingsSmtpLazyRoute
  '/app/admin/settings/translations-localization': typeof AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute
  '/app/admin/settings/upload': typeof AppAppAdminAdminSettingsSettingsUploadLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/app/_app': typeof AppAppRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/auth/join': typeof AuthAuthJoinRoute
  '/_auth/auth/password-reset': typeof AuthAuthPasswordResetRoute
  '/_auth/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/app/_app/test': typeof AppAppTestRoute
  '/app/_app/announcements': typeof AppAppAnnouncementsLazyRoute
  '/app/_app/': typeof AppAppIndexRoute
  '/app/_app/account': typeof AppAppAccountRouteWithChildren
  '/app/_app/account/_account': typeof AppAppAccountAccountRouteWithChildren
  '/app/_app/admin': typeof AppAppAdminRouteWithChildren
  '/app/_app/admin/_admin': typeof AppAppAdminAdminRouteWithChildren
  '/app/_app/development': typeof AppAppDevelopmentRouteWithChildren
  '/app/_app/development/_development': typeof AppAppDevelopmentDevelopmentRouteWithChildren
  '/app/_app/hr': typeof AppAppHrRouteWithChildren
  '/app/_app/hr/_hr': typeof AppAppHrHrRouteWithChildren
  '/app/_app/manager': typeof AppAppManagerRouteWithChildren
  '/app/_app/manager/_manager': typeof AppAppManagerManagerRouteWithChildren
  '/app/_app/chats/': typeof AppAppChatsIndexLazyRoute
  '/app/_app/account/_account/drive': typeof AppAppAccountAccountDriveLazyRoute
  '/app/_app/account/_account/projects': typeof AppAppAccountAccountProjectsLazyRoute
  '/app/_app/account/_account/requests': typeof AppAppAccountAccountRequestsLazyRoute
  '/app/_app/admin/_admin/activity-monitor': typeof AppAppAdminAdminActivityMonitorLazyRoute
  '/app/_app/admin/_admin/api-keys': typeof AppAppAdminAdminApiKeysLazyRoute
  '/app/_app/admin/_admin/backup': typeof AppAppAdminAdminBackupLazyRoute
  '/app/_app/admin/_admin/docs': typeof AppAppAdminAdminDocsLazyLazyRoute
  '/app/_app/development/_development/repositories': typeof AppAppDevelopmentDevelopmentRepositoriesLazyRoute
  '/app/_app/development/_development/terminal': typeof AppAppDevelopmentDevelopmentTerminalLazyRoute
  '/app/_app/development/_development/tickets': typeof AppAppDevelopmentDevelopmentTicketsLazyRoute
  '/app/_app/development/_development/toolkit': typeof AppAppDevelopmentDevelopmentToolkitLazyRoute
  '/app/_app/hr/_hr/attendance': typeof AppAppHrHrAttendanceLazyRoute
  '/app/_app/hr/_hr/calendar': typeof AppAppHrHrCalendarLazyRoute
  '/app/_app/hr/_hr/employees': typeof AppAppHrHrEmployeesLazyRoute
  '/app/_app/hr/_hr/leave-management': typeof AppAppHrHrLeaveManagementLazyRoute
  '/app/_app/hr/_hr/manage-requests': typeof AppAppHrHrManageRequestsLazyRoute
  '/app/_app/hr/_hr/notes': typeof AppAppHrHrNotesLazyRoute
  '/app/_app/account/_account/profile': typeof AppAppAccountAccountProfileRouteWithChildren
  '/app/_app/account/_account/profile/_profile': typeof AppAppAccountAccountProfileProfileRouteWithChildren
  '/app/_app/admin/_admin/configuration': typeof AppAppAdminAdminConfigurationRouteWithChildren
  '/app/_app/admin/_admin/configuration/_configuration': typeof AppAppAdminAdminConfigurationConfigurationRouteWithChildren
  '/app/_app/admin/_admin/settings': typeof AppAppAdminAdminSettingsRouteWithChildren
  '/app/_app/admin/_admin/settings/_settings': typeof AppAppAdminAdminSettingsSettingsRouteWithChildren
  '/app/_app/admin/_admin/servers-db/': typeof AppAppAdminAdminServersDbIndexRoute
  '/app/_app/manager/_manager/tracking/': typeof AppAppManagerManagerTrackingIndexRoute
  '/app/_app/admin/_admin/settings/_settings/about': typeof AppAppAdminAdminSettingsSettingsAboutLazyRoute
  '/app/_app/admin/_admin/settings/_settings/amc': typeof AppAppAdminAdminSettingsSettingsAmcLazyRoute
  '/app/_app/admin/_admin/settings/_settings/api-keys': typeof AppAppAdminAdminSettingsSettingsApiKeysLazyRoute
  '/app/_app/admin/_admin/settings/_settings/appearance-theme': typeof AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute
  '/app/_app/admin/_admin/settings/_settings/backup': typeof AppAppAdminAdminSettingsSettingsBackupLazyRoute
  '/app/_app/admin/_admin/settings/_settings/companies': typeof AppAppAdminAdminSettingsSettingsCompaniesLazyRoute
  '/app/_app/admin/_admin/settings/_settings/drive': typeof AppAppAdminAdminSettingsSettingsDriveLazyRoute
  '/app/_app/admin/_admin/settings/_settings/help-support': typeof AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute
  '/app/_app/admin/_admin/settings/_settings/languages-region': typeof AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute
  '/app/_app/admin/_admin/settings/_settings/license': typeof AppAppAdminAdminSettingsSettingsLicenseLazyRoute
  '/app/_app/admin/_admin/settings/_settings/log-settings': typeof AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute
  '/app/_app/admin/_admin/settings/_settings/meta-data': typeof AppAppAdminAdminSettingsSettingsMetaDataLazyRoute
  '/app/_app/admin/_admin/settings/_settings/mobile-apps': typeof AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute
  '/app/_app/admin/_admin/settings/_settings/notifications': typeof AppAppAdminAdminSettingsSettingsNotificationsLazyRoute
  '/app/_app/admin/_admin/settings/_settings/payments-billing': typeof AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute
  '/app/_app/admin/_admin/settings/_settings/role-management': typeof AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute
  '/app/_app/admin/_admin/settings/_settings/security': typeof AppAppAdminAdminSettingsSettingsSecurityLazyRoute
  '/app/_app/admin/_admin/settings/_settings/smtp': typeof AppAppAdminAdminSettingsSettingsSmtpLazyRoute
  '/app/_app/admin/_admin/settings/_settings/translations-localization': typeof AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute
  '/app/_app/admin/_admin/settings/_settings/upload': typeof AppAppAdminAdminSettingsSettingsUploadLazyRoute
  '/app/_app/admin/_admin/configuration/_configuration/': typeof AppAppAdminAdminConfigurationConfigurationIndexRoute
  '/app/_app/account/_account/profile/_profile/': typeof AppAppAccountAccountProfileProfileIndexLazyRoute
  '/app/_app/admin/_admin/settings/_settings/': typeof AppAppAdminAdminSettingsSettingsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/'
    | '/auth/join'
    | '/auth/password-reset'
    | '/auth/verify-email'
    | '/app/test'
    | '/app/announcements'
    | '/app/'
    | '/app/account'
    | '/app/admin'
    | '/app/development'
    | '/app/hr'
    | '/app/manager'
    | '/app/chats'
    | '/app/account/drive'
    | '/app/account/projects'
    | '/app/account/requests'
    | '/app/admin/activity-monitor'
    | '/app/admin/api-keys'
    | '/app/admin/backup'
    | '/app/admin/docs'
    | '/app/development/repositories'
    | '/app/development/terminal'
    | '/app/development/tickets'
    | '/app/development/toolkit'
    | '/app/hr/attendance'
    | '/app/hr/calendar'
    | '/app/hr/employees'
    | '/app/hr/leave-management'
    | '/app/hr/manage-requests'
    | '/app/hr/notes'
    | '/app/account/profile'
    | '/app/admin/configuration'
    | '/app/admin/settings'
    | '/app/admin/servers-db'
    | '/app/manager/tracking'
    | '/app/admin/settings/about'
    | '/app/admin/settings/amc'
    | '/app/admin/settings/api-keys'
    | '/app/admin/settings/appearance-theme'
    | '/app/admin/settings/backup'
    | '/app/admin/settings/companies'
    | '/app/admin/settings/drive'
    | '/app/admin/settings/help-support'
    | '/app/admin/settings/languages-region'
    | '/app/admin/settings/license'
    | '/app/admin/settings/log-settings'
    | '/app/admin/settings/meta-data'
    | '/app/admin/settings/mobile-apps'
    | '/app/admin/settings/notifications'
    | '/app/admin/settings/payments-billing'
    | '/app/admin/settings/role-management'
    | '/app/admin/settings/security'
    | '/app/admin/settings/smtp'
    | '/app/admin/settings/translations-localization'
    | '/app/admin/settings/upload'
    | '/app/admin/configuration/'
    | '/app/account/profile/'
    | '/app/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/'
    | '/auth/join'
    | '/auth/password-reset'
    | '/auth/verify-email'
    | '/app/test'
    | '/app/announcements'
    | '/app/account'
    | '/app/admin'
    | '/app/development'
    | '/app/hr'
    | '/app/manager'
    | '/app/chats'
    | '/app/account/drive'
    | '/app/account/projects'
    | '/app/account/requests'
    | '/app/admin/activity-monitor'
    | '/app/admin/api-keys'
    | '/app/admin/backup'
    | '/app/admin/docs'
    | '/app/development/repositories'
    | '/app/development/terminal'
    | '/app/development/tickets'
    | '/app/development/toolkit'
    | '/app/hr/attendance'
    | '/app/hr/calendar'
    | '/app/hr/employees'
    | '/app/hr/leave-management'
    | '/app/hr/manage-requests'
    | '/app/hr/notes'
    | '/app/account/profile'
    | '/app/admin/configuration'
    | '/app/admin/settings'
    | '/app/admin/servers-db'
    | '/app/manager/tracking'
    | '/app/admin/settings/about'
    | '/app/admin/settings/amc'
    | '/app/admin/settings/api-keys'
    | '/app/admin/settings/appearance-theme'
    | '/app/admin/settings/backup'
    | '/app/admin/settings/companies'
    | '/app/admin/settings/drive'
    | '/app/admin/settings/help-support'
    | '/app/admin/settings/languages-region'
    | '/app/admin/settings/license'
    | '/app/admin/settings/log-settings'
    | '/app/admin/settings/meta-data'
    | '/app/admin/settings/mobile-apps'
    | '/app/admin/settings/notifications'
    | '/app/admin/settings/payments-billing'
    | '/app/admin/settings/role-management'
    | '/app/admin/settings/security'
    | '/app/admin/settings/smtp'
    | '/app/admin/settings/translations-localization'
    | '/app/admin/settings/upload'
  id:
    | '__root__'
    | '/_auth'
    | '/app'
    | '/app/_app'
    | '/_auth/'
    | '/_auth/auth/join'
    | '/_auth/auth/password-reset'
    | '/_auth/auth/verify-email'
    | '/app/_app/test'
    | '/app/_app/announcements'
    | '/app/_app/'
    | '/app/_app/account'
    | '/app/_app/account/_account'
    | '/app/_app/admin'
    | '/app/_app/admin/_admin'
    | '/app/_app/development'
    | '/app/_app/development/_development'
    | '/app/_app/hr'
    | '/app/_app/hr/_hr'
    | '/app/_app/manager'
    | '/app/_app/manager/_manager'
    | '/app/_app/chats/'
    | '/app/_app/account/_account/drive'
    | '/app/_app/account/_account/projects'
    | '/app/_app/account/_account/requests'
    | '/app/_app/admin/_admin/activity-monitor'
    | '/app/_app/admin/_admin/api-keys'
    | '/app/_app/admin/_admin/backup'
    | '/app/_app/admin/_admin/docs'
    | '/app/_app/development/_development/repositories'
    | '/app/_app/development/_development/terminal'
    | '/app/_app/development/_development/tickets'
    | '/app/_app/development/_development/toolkit'
    | '/app/_app/hr/_hr/attendance'
    | '/app/_app/hr/_hr/calendar'
    | '/app/_app/hr/_hr/employees'
    | '/app/_app/hr/_hr/leave-management'
    | '/app/_app/hr/_hr/manage-requests'
    | '/app/_app/hr/_hr/notes'
    | '/app/_app/account/_account/profile'
    | '/app/_app/account/_account/profile/_profile'
    | '/app/_app/admin/_admin/configuration'
    | '/app/_app/admin/_admin/configuration/_configuration'
    | '/app/_app/admin/_admin/settings'
    | '/app/_app/admin/_admin/settings/_settings'
    | '/app/_app/admin/_admin/servers-db/'
    | '/app/_app/manager/_manager/tracking/'
    | '/app/_app/admin/_admin/settings/_settings/about'
    | '/app/_app/admin/_admin/settings/_settings/amc'
    | '/app/_app/admin/_admin/settings/_settings/api-keys'
    | '/app/_app/admin/_admin/settings/_settings/appearance-theme'
    | '/app/_app/admin/_admin/settings/_settings/backup'
    | '/app/_app/admin/_admin/settings/_settings/companies'
    | '/app/_app/admin/_admin/settings/_settings/drive'
    | '/app/_app/admin/_admin/settings/_settings/help-support'
    | '/app/_app/admin/_admin/settings/_settings/languages-region'
    | '/app/_app/admin/_admin/settings/_settings/license'
    | '/app/_app/admin/_admin/settings/_settings/log-settings'
    | '/app/_app/admin/_admin/settings/_settings/meta-data'
    | '/app/_app/admin/_admin/settings/_settings/mobile-apps'
    | '/app/_app/admin/_admin/settings/_settings/notifications'
    | '/app/_app/admin/_admin/settings/_settings/payments-billing'
    | '/app/_app/admin/_admin/settings/_settings/role-management'
    | '/app/_app/admin/_admin/settings/_settings/security'
    | '/app/_app/admin/_admin/settings/_settings/smtp'
    | '/app/_app/admin/_admin/settings/_settings/translations-localization'
    | '/app/_app/admin/_admin/settings/_settings/upload'
    | '/app/_app/admin/_admin/configuration/_configuration/'
    | '/app/_app/account/_account/profile/_profile/'
    | '/app/_app/admin/_admin/settings/_settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/_app': {
      id: '/app/_app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_app/manager': {
      id: '/app/_app/manager'
      path: '/manager'
      fullPath: '/app/manager'
      preLoaderRoute: typeof AppAppManagerRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/hr': {
      id: '/app/_app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppAppHrRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/development': {
      id: '/app/_app/development'
      path: '/development'
      fullPath: '/app/development'
      preLoaderRoute: typeof AppAppDevelopmentRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/admin': {
      id: '/app/_app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAppAdminRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/account': {
      id: '/app/_app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAppAccountRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/announcements': {
      id: '/app/_app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAppAnnouncementsLazyRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/test': {
      id: '/app/_app/test'
      path: '/test'
      fullPath: '/app/test'
      preLoaderRoute: typeof AppAppTestRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_auth/auth/verify-email': {
      id: '/_auth/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthAuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/password-reset': {
      id: '/_auth/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthAuthPasswordResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/join': {
      id: '/_auth/auth/join'
      path: '/auth/join'
      fullPath: '/auth/join'
      preLoaderRoute: typeof AuthAuthJoinRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/_app/chats/': {
      id: '/app/_app/chats/'
      path: '/chats'
      fullPath: '/app/chats'
      preLoaderRoute: typeof AppAppChatsIndexLazyRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/manager/_manager': {
      id: '/app/_app/manager/_manager'
      path: '/manager'
      fullPath: '/app/manager'
      preLoaderRoute: typeof AppAppManagerManagerRouteImport
      parentRoute: typeof AppAppManagerRoute
    }
    '/app/_app/hr/_hr': {
      id: '/app/_app/hr/_hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppAppHrHrRouteImport
      parentRoute: typeof AppAppHrRoute
    }
    '/app/_app/development/_development': {
      id: '/app/_app/development/_development'
      path: '/development'
      fullPath: '/app/development'
      preLoaderRoute: typeof AppAppDevelopmentDevelopmentRouteImport
      parentRoute: typeof AppAppDevelopmentRoute
    }
    '/app/_app/admin/_admin': {
      id: '/app/_app/admin/_admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAppAdminAdminRouteImport
      parentRoute: typeof AppAppAdminRoute
    }
    '/app/_app/account/_account': {
      id: '/app/_app/account/_account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAppAccountAccountRouteImport
      parentRoute: typeof AppAppAccountRoute
    }
    '/app/_app/admin/_admin/settings': {
      id: '/app/_app/admin/_admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAppAdminAdminSettingsRouteImport
      parentRoute: typeof AppAppAdminAdminRoute
    }
    '/app/_app/admin/_admin/configuration': {
      id: '/app/_app/admin/_admin/configuration'
      path: '/configuration'
      fullPath: '/app/admin/configuration'
      preLoaderRoute: typeof AppAppAdminAdminConfigurationRouteImport
      parentRoute: typeof AppAppAdminAdminRoute
    }
    '/app/_app/account/_account/profile': {
      id: '/app/_app/account/_account/profile'
      path: '/profile'
      fullPath: '/app/account/profile'
      preLoaderRoute: typeof AppAppAccountAccountProfileRouteImport
      parentRoute: typeof AppAppAccountAccountRoute
    }
    '/app/_app/hr/_hr/notes': {
      id: '/app/_app/hr/_hr/notes'
      path: '/notes'
      fullPath: '/app/hr/notes'
      preLoaderRoute: typeof AppAppHrHrNotesLazyRouteImport
      parentRoute: typeof AppAppHrHrRoute
    }
    '/app/_app/hr/_hr/manage-requests': {
      id: '/app/_app/hr/_hr/manage-requests'
      path: '/manage-requests'
      fullPath: '/app/hr/manage-requests'
      preLoaderRoute: typeof AppAppHrHrManageRequestsLazyRouteImport
      parentRoute: typeof AppAppHrHrRoute
    }
    '/app/_app/hr/_hr/leave-management': {
      id: '/app/_app/hr/_hr/leave-management'
      path: '/leave-management'
      fullPath: '/app/hr/leave-management'
      preLoaderRoute: typeof AppAppHrHrLeaveManagementLazyRouteImport
      parentRoute: typeof AppAppHrHrRoute
    }
    '/app/_app/hr/_hr/employees': {
      id: '/app/_app/hr/_hr/employees'
      path: '/employees'
      fullPath: '/app/hr/employees'
      preLoaderRoute: typeof AppAppHrHrEmployeesLazyRouteImport
      parentRoute: typeof AppAppHrHrRoute
    }
    '/app/_app/hr/_hr/calendar': {
      id: '/app/_app/hr/_hr/calendar'
      path: '/calendar'
      fullPath: '/app/hr/calendar'
      preLoaderRoute: typeof AppAppHrHrCalendarLazyRouteImport
      parentRoute: typeof AppAppHrHrRoute
    }
    '/app/_app/hr/_hr/attendance': {
      id: '/app/_app/hr/_hr/attendance'
      path: '/attendance'
      fullPath: '/app/hr/attendance'
      preLoaderRoute: typeof AppAppHrHrAttendanceLazyRouteImport
      parentRoute: typeof AppAppHrHrRoute
    }
    '/app/_app/development/_development/toolkit': {
      id: '/app/_app/development/_development/toolkit'
      path: '/toolkit'
      fullPath: '/app/development/toolkit'
      preLoaderRoute: typeof AppAppDevelopmentDevelopmentToolkitLazyRouteImport
      parentRoute: typeof AppAppDevelopmentDevelopmentRoute
    }
    '/app/_app/development/_development/tickets': {
      id: '/app/_app/development/_development/tickets'
      path: '/tickets'
      fullPath: '/app/development/tickets'
      preLoaderRoute: typeof AppAppDevelopmentDevelopmentTicketsLazyRouteImport
      parentRoute: typeof AppAppDevelopmentDevelopmentRoute
    }
    '/app/_app/development/_development/terminal': {
      id: '/app/_app/development/_development/terminal'
      path: '/terminal'
      fullPath: '/app/development/terminal'
      preLoaderRoute: typeof AppAppDevelopmentDevelopmentTerminalLazyRouteImport
      parentRoute: typeof AppAppDevelopmentDevelopmentRoute
    }
    '/app/_app/development/_development/repositories': {
      id: '/app/_app/development/_development/repositories'
      path: '/repositories'
      fullPath: '/app/development/repositories'
      preLoaderRoute: typeof AppAppDevelopmentDevelopmentRepositoriesLazyRouteImport
      parentRoute: typeof AppAppDevelopmentDevelopmentRoute
    }
    '/app/_app/admin/_admin/docs': {
      id: '/app/_app/admin/_admin/docs'
      path: '/docs'
      fullPath: '/app/admin/docs'
      preLoaderRoute: typeof AppAppAdminAdminDocsLazyLazyRouteImport
      parentRoute: typeof AppAppAdminAdminRoute
    }
    '/app/_app/admin/_admin/backup': {
      id: '/app/_app/admin/_admin/backup'
      path: '/backup'
      fullPath: '/app/admin/backup'
      preLoaderRoute: typeof AppAppAdminAdminBackupLazyRouteImport
      parentRoute: typeof AppAppAdminAdminRoute
    }
    '/app/_app/admin/_admin/api-keys': {
      id: '/app/_app/admin/_admin/api-keys'
      path: '/api-keys'
      fullPath: '/app/admin/api-keys'
      preLoaderRoute: typeof AppAppAdminAdminApiKeysLazyRouteImport
      parentRoute: typeof AppAppAdminAdminRoute
    }
    '/app/_app/admin/_admin/activity-monitor': {
      id: '/app/_app/admin/_admin/activity-monitor'
      path: '/activity-monitor'
      fullPath: '/app/admin/activity-monitor'
      preLoaderRoute: typeof AppAppAdminAdminActivityMonitorLazyRouteImport
      parentRoute: typeof AppAppAdminAdminRoute
    }
    '/app/_app/account/_account/requests': {
      id: '/app/_app/account/_account/requests'
      path: '/requests'
      fullPath: '/app/account/requests'
      preLoaderRoute: typeof AppAppAccountAccountRequestsLazyRouteImport
      parentRoute: typeof AppAppAccountAccountRoute
    }
    '/app/_app/account/_account/projects': {
      id: '/app/_app/account/_account/projects'
      path: '/projects'
      fullPath: '/app/account/projects'
      preLoaderRoute: typeof AppAppAccountAccountProjectsLazyRouteImport
      parentRoute: typeof AppAppAccountAccountRoute
    }
    '/app/_app/account/_account/drive': {
      id: '/app/_app/account/_account/drive'
      path: '/drive'
      fullPath: '/app/account/drive'
      preLoaderRoute: typeof AppAppAccountAccountDriveLazyRouteImport
      parentRoute: typeof AppAppAccountAccountRoute
    }
    '/app/_app/manager/_manager/tracking/': {
      id: '/app/_app/manager/_manager/tracking/'
      path: '/tracking'
      fullPath: '/app/manager/tracking'
      preLoaderRoute: typeof AppAppManagerManagerTrackingIndexRouteImport
      parentRoute: typeof AppAppManagerManagerRoute
    }
    '/app/_app/admin/_admin/servers-db/': {
      id: '/app/_app/admin/_admin/servers-db/'
      path: '/servers-db'
      fullPath: '/app/admin/servers-db'
      preLoaderRoute: typeof AppAppAdminAdminServersDbIndexRouteImport
      parentRoute: typeof AppAppAdminAdminRoute
    }
    '/app/_app/admin/_admin/settings/_settings': {
      id: '/app/_app/admin/_admin/settings/_settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsRoute
    }
    '/app/_app/admin/_admin/configuration/_configuration': {
      id: '/app/_app/admin/_admin/configuration/_configuration'
      path: '/configuration'
      fullPath: '/app/admin/configuration'
      preLoaderRoute: typeof AppAppAdminAdminConfigurationConfigurationRouteImport
      parentRoute: typeof AppAppAdminAdminConfigurationRoute
    }
    '/app/_app/account/_account/profile/_profile': {
      id: '/app/_app/account/_account/profile/_profile'
      path: '/profile'
      fullPath: '/app/account/profile'
      preLoaderRoute: typeof AppAppAccountAccountProfileProfileRouteImport
      parentRoute: typeof AppAppAccountAccountProfileRoute
    }
    '/app/_app/admin/_admin/settings/_settings/': {
      id: '/app/_app/admin/_admin/settings/_settings/'
      path: '/'
      fullPath: '/app/admin/settings/'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsIndexLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/account/_account/profile/_profile/': {
      id: '/app/_app/account/_account/profile/_profile/'
      path: '/'
      fullPath: '/app/account/profile/'
      preLoaderRoute: typeof AppAppAccountAccountProfileProfileIndexLazyRouteImport
      parentRoute: typeof AppAppAccountAccountProfileProfileRoute
    }
    '/app/_app/admin/_admin/configuration/_configuration/': {
      id: '/app/_app/admin/_admin/configuration/_configuration/'
      path: '/'
      fullPath: '/app/admin/configuration/'
      preLoaderRoute: typeof AppAppAdminAdminConfigurationConfigurationIndexRouteImport
      parentRoute: typeof AppAppAdminAdminConfigurationConfigurationRoute
    }
    '/app/_app/admin/_admin/settings/_settings/upload': {
      id: '/app/_app/admin/_admin/settings/_settings/upload'
      path: '/upload'
      fullPath: '/app/admin/settings/upload'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsUploadLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/translations-localization': {
      id: '/app/_app/admin/_admin/settings/_settings/translations-localization'
      path: '/translations-localization'
      fullPath: '/app/admin/settings/translations-localization'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/smtp': {
      id: '/app/_app/admin/_admin/settings/_settings/smtp'
      path: '/smtp'
      fullPath: '/app/admin/settings/smtp'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsSmtpLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/security': {
      id: '/app/_app/admin/_admin/settings/_settings/security'
      path: '/security'
      fullPath: '/app/admin/settings/security'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsSecurityLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/role-management': {
      id: '/app/_app/admin/_admin/settings/_settings/role-management'
      path: '/role-management'
      fullPath: '/app/admin/settings/role-management'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsRoleManagementLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/payments-billing': {
      id: '/app/_app/admin/_admin/settings/_settings/payments-billing'
      path: '/payments-billing'
      fullPath: '/app/admin/settings/payments-billing'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/notifications': {
      id: '/app/_app/admin/_admin/settings/_settings/notifications'
      path: '/notifications'
      fullPath: '/app/admin/settings/notifications'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsNotificationsLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/mobile-apps': {
      id: '/app/_app/admin/_admin/settings/_settings/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/app/admin/settings/mobile-apps'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsMobileAppsLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/meta-data': {
      id: '/app/_app/admin/_admin/settings/_settings/meta-data'
      path: '/meta-data'
      fullPath: '/app/admin/settings/meta-data'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsMetaDataLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/log-settings': {
      id: '/app/_app/admin/_admin/settings/_settings/log-settings'
      path: '/log-settings'
      fullPath: '/app/admin/settings/log-settings'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsLogSettingsLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/license': {
      id: '/app/_app/admin/_admin/settings/_settings/license'
      path: '/license'
      fullPath: '/app/admin/settings/license'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsLicenseLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/languages-region': {
      id: '/app/_app/admin/_admin/settings/_settings/languages-region'
      path: '/languages-region'
      fullPath: '/app/admin/settings/languages-region'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/help-support': {
      id: '/app/_app/admin/_admin/settings/_settings/help-support'
      path: '/help-support'
      fullPath: '/app/admin/settings/help-support'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsHelpSupportLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/drive': {
      id: '/app/_app/admin/_admin/settings/_settings/drive'
      path: '/drive'
      fullPath: '/app/admin/settings/drive'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsDriveLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/companies': {
      id: '/app/_app/admin/_admin/settings/_settings/companies'
      path: '/companies'
      fullPath: '/app/admin/settings/companies'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsCompaniesLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/backup': {
      id: '/app/_app/admin/_admin/settings/_settings/backup'
      path: '/backup'
      fullPath: '/app/admin/settings/backup'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsBackupLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/appearance-theme': {
      id: '/app/_app/admin/_admin/settings/_settings/appearance-theme'
      path: '/appearance-theme'
      fullPath: '/app/admin/settings/appearance-theme'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/api-keys': {
      id: '/app/_app/admin/_admin/settings/_settings/api-keys'
      path: '/api-keys'
      fullPath: '/app/admin/settings/api-keys'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsApiKeysLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/amc': {
      id: '/app/_app/admin/_admin/settings/_settings/amc'
      path: '/amc'
      fullPath: '/app/admin/settings/amc'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsAmcLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
    '/app/_app/admin/_admin/settings/_settings/about': {
      id: '/app/_app/admin/_admin/settings/_settings/about'
      path: '/about'
      fullPath: '/app/admin/settings/about'
      preLoaderRoute: typeof AppAppAdminAdminSettingsSettingsAboutLazyRouteImport
      parentRoute: typeof AppAppAdminAdminSettingsSettingsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAuthJoinRoute: typeof AuthAuthJoinRoute
  AuthAuthPasswordResetRoute: typeof AuthAuthPasswordResetRoute
  AuthAuthVerifyEmailRoute: typeof AuthAuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAuthJoinRoute: AuthAuthJoinRoute,
  AuthAuthPasswordResetRoute: AuthAuthPasswordResetRoute,
  AuthAuthVerifyEmailRoute: AuthAuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppAppAccountAccountProfileProfileRouteChildren {
  AppAppAccountAccountProfileProfileIndexLazyRoute: typeof AppAppAccountAccountProfileProfileIndexLazyRoute
}

const AppAppAccountAccountProfileProfileRouteChildren: AppAppAccountAccountProfileProfileRouteChildren =
  {
    AppAppAccountAccountProfileProfileIndexLazyRoute:
      AppAppAccountAccountProfileProfileIndexLazyRoute,
  }

const AppAppAccountAccountProfileProfileRouteWithChildren =
  AppAppAccountAccountProfileProfileRoute._addFileChildren(
    AppAppAccountAccountProfileProfileRouteChildren,
  )

interface AppAppAccountAccountProfileRouteChildren {
  AppAppAccountAccountProfileProfileRoute: typeof AppAppAccountAccountProfileProfileRouteWithChildren
}

const AppAppAccountAccountProfileRouteChildren: AppAppAccountAccountProfileRouteChildren =
  {
    AppAppAccountAccountProfileProfileRoute:
      AppAppAccountAccountProfileProfileRouteWithChildren,
  }

const AppAppAccountAccountProfileRouteWithChildren =
  AppAppAccountAccountProfileRoute._addFileChildren(
    AppAppAccountAccountProfileRouteChildren,
  )

interface AppAppAccountAccountRouteChildren {
  AppAppAccountAccountDriveLazyRoute: typeof AppAppAccountAccountDriveLazyRoute
  AppAppAccountAccountProjectsLazyRoute: typeof AppAppAccountAccountProjectsLazyRoute
  AppAppAccountAccountRequestsLazyRoute: typeof AppAppAccountAccountRequestsLazyRoute
  AppAppAccountAccountProfileRoute: typeof AppAppAccountAccountProfileRouteWithChildren
}

const AppAppAccountAccountRouteChildren: AppAppAccountAccountRouteChildren = {
  AppAppAccountAccountDriveLazyRoute: AppAppAccountAccountDriveLazyRoute,
  AppAppAccountAccountProjectsLazyRoute: AppAppAccountAccountProjectsLazyRoute,
  AppAppAccountAccountRequestsLazyRoute: AppAppAccountAccountRequestsLazyRoute,
  AppAppAccountAccountProfileRoute:
    AppAppAccountAccountProfileRouteWithChildren,
}

const AppAppAccountAccountRouteWithChildren =
  AppAppAccountAccountRoute._addFileChildren(AppAppAccountAccountRouteChildren)

interface AppAppAccountRouteChildren {
  AppAppAccountAccountRoute: typeof AppAppAccountAccountRouteWithChildren
}

const AppAppAccountRouteChildren: AppAppAccountRouteChildren = {
  AppAppAccountAccountRoute: AppAppAccountAccountRouteWithChildren,
}

const AppAppAccountRouteWithChildren = AppAppAccountRoute._addFileChildren(
  AppAppAccountRouteChildren,
)

interface AppAppAdminAdminConfigurationConfigurationRouteChildren {
  AppAppAdminAdminConfigurationConfigurationIndexRoute: typeof AppAppAdminAdminConfigurationConfigurationIndexRoute
}

const AppAppAdminAdminConfigurationConfigurationRouteChildren: AppAppAdminAdminConfigurationConfigurationRouteChildren =
  {
    AppAppAdminAdminConfigurationConfigurationIndexRoute:
      AppAppAdminAdminConfigurationConfigurationIndexRoute,
  }

const AppAppAdminAdminConfigurationConfigurationRouteWithChildren =
  AppAppAdminAdminConfigurationConfigurationRoute._addFileChildren(
    AppAppAdminAdminConfigurationConfigurationRouteChildren,
  )

interface AppAppAdminAdminConfigurationRouteChildren {
  AppAppAdminAdminConfigurationConfigurationRoute: typeof AppAppAdminAdminConfigurationConfigurationRouteWithChildren
}

const AppAppAdminAdminConfigurationRouteChildren: AppAppAdminAdminConfigurationRouteChildren =
  {
    AppAppAdminAdminConfigurationConfigurationRoute:
      AppAppAdminAdminConfigurationConfigurationRouteWithChildren,
  }

const AppAppAdminAdminConfigurationRouteWithChildren =
  AppAppAdminAdminConfigurationRoute._addFileChildren(
    AppAppAdminAdminConfigurationRouteChildren,
  )

interface AppAppAdminAdminSettingsSettingsRouteChildren {
  AppAppAdminAdminSettingsSettingsAboutLazyRoute: typeof AppAppAdminAdminSettingsSettingsAboutLazyRoute
  AppAppAdminAdminSettingsSettingsAmcLazyRoute: typeof AppAppAdminAdminSettingsSettingsAmcLazyRoute
  AppAppAdminAdminSettingsSettingsApiKeysLazyRoute: typeof AppAppAdminAdminSettingsSettingsApiKeysLazyRoute
  AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute: typeof AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute
  AppAppAdminAdminSettingsSettingsBackupLazyRoute: typeof AppAppAdminAdminSettingsSettingsBackupLazyRoute
  AppAppAdminAdminSettingsSettingsCompaniesLazyRoute: typeof AppAppAdminAdminSettingsSettingsCompaniesLazyRoute
  AppAppAdminAdminSettingsSettingsDriveLazyRoute: typeof AppAppAdminAdminSettingsSettingsDriveLazyRoute
  AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute: typeof AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute
  AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute: typeof AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute
  AppAppAdminAdminSettingsSettingsLicenseLazyRoute: typeof AppAppAdminAdminSettingsSettingsLicenseLazyRoute
  AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute: typeof AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute
  AppAppAdminAdminSettingsSettingsMetaDataLazyRoute: typeof AppAppAdminAdminSettingsSettingsMetaDataLazyRoute
  AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute: typeof AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute
  AppAppAdminAdminSettingsSettingsNotificationsLazyRoute: typeof AppAppAdminAdminSettingsSettingsNotificationsLazyRoute
  AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute: typeof AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute
  AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute: typeof AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute
  AppAppAdminAdminSettingsSettingsSecurityLazyRoute: typeof AppAppAdminAdminSettingsSettingsSecurityLazyRoute
  AppAppAdminAdminSettingsSettingsSmtpLazyRoute: typeof AppAppAdminAdminSettingsSettingsSmtpLazyRoute
  AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute: typeof AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute
  AppAppAdminAdminSettingsSettingsUploadLazyRoute: typeof AppAppAdminAdminSettingsSettingsUploadLazyRoute
  AppAppAdminAdminSettingsSettingsIndexLazyRoute: typeof AppAppAdminAdminSettingsSettingsIndexLazyRoute
}

const AppAppAdminAdminSettingsSettingsRouteChildren: AppAppAdminAdminSettingsSettingsRouteChildren =
  {
    AppAppAdminAdminSettingsSettingsAboutLazyRoute:
      AppAppAdminAdminSettingsSettingsAboutLazyRoute,
    AppAppAdminAdminSettingsSettingsAmcLazyRoute:
      AppAppAdminAdminSettingsSettingsAmcLazyRoute,
    AppAppAdminAdminSettingsSettingsApiKeysLazyRoute:
      AppAppAdminAdminSettingsSettingsApiKeysLazyRoute,
    AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute:
      AppAppAdminAdminSettingsSettingsAppearanceThemeLazyRoute,
    AppAppAdminAdminSettingsSettingsBackupLazyRoute:
      AppAppAdminAdminSettingsSettingsBackupLazyRoute,
    AppAppAdminAdminSettingsSettingsCompaniesLazyRoute:
      AppAppAdminAdminSettingsSettingsCompaniesLazyRoute,
    AppAppAdminAdminSettingsSettingsDriveLazyRoute:
      AppAppAdminAdminSettingsSettingsDriveLazyRoute,
    AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute:
      AppAppAdminAdminSettingsSettingsHelpSupportLazyRoute,
    AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute:
      AppAppAdminAdminSettingsSettingsLanguagesRegionLazyRoute,
    AppAppAdminAdminSettingsSettingsLicenseLazyRoute:
      AppAppAdminAdminSettingsSettingsLicenseLazyRoute,
    AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute:
      AppAppAdminAdminSettingsSettingsLogSettingsLazyRoute,
    AppAppAdminAdminSettingsSettingsMetaDataLazyRoute:
      AppAppAdminAdminSettingsSettingsMetaDataLazyRoute,
    AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute:
      AppAppAdminAdminSettingsSettingsMobileAppsLazyRoute,
    AppAppAdminAdminSettingsSettingsNotificationsLazyRoute:
      AppAppAdminAdminSettingsSettingsNotificationsLazyRoute,
    AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute:
      AppAppAdminAdminSettingsSettingsPaymentsBillingLazyRoute,
    AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute:
      AppAppAdminAdminSettingsSettingsRoleManagementLazyRoute,
    AppAppAdminAdminSettingsSettingsSecurityLazyRoute:
      AppAppAdminAdminSettingsSettingsSecurityLazyRoute,
    AppAppAdminAdminSettingsSettingsSmtpLazyRoute:
      AppAppAdminAdminSettingsSettingsSmtpLazyRoute,
    AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute:
      AppAppAdminAdminSettingsSettingsTranslationsLocalizationLazyRoute,
    AppAppAdminAdminSettingsSettingsUploadLazyRoute:
      AppAppAdminAdminSettingsSettingsUploadLazyRoute,
    AppAppAdminAdminSettingsSettingsIndexLazyRoute:
      AppAppAdminAdminSettingsSettingsIndexLazyRoute,
  }

const AppAppAdminAdminSettingsSettingsRouteWithChildren =
  AppAppAdminAdminSettingsSettingsRoute._addFileChildren(
    AppAppAdminAdminSettingsSettingsRouteChildren,
  )

interface AppAppAdminAdminSettingsRouteChildren {
  AppAppAdminAdminSettingsSettingsRoute: typeof AppAppAdminAdminSettingsSettingsRouteWithChildren
}

const AppAppAdminAdminSettingsRouteChildren: AppAppAdminAdminSettingsRouteChildren =
  {
    AppAppAdminAdminSettingsSettingsRoute:
      AppAppAdminAdminSettingsSettingsRouteWithChildren,
  }

const AppAppAdminAdminSettingsRouteWithChildren =
  AppAppAdminAdminSettingsRoute._addFileChildren(
    AppAppAdminAdminSettingsRouteChildren,
  )

interface AppAppAdminAdminRouteChildren {
  AppAppAdminAdminActivityMonitorLazyRoute: typeof AppAppAdminAdminActivityMonitorLazyRoute
  AppAppAdminAdminApiKeysLazyRoute: typeof AppAppAdminAdminApiKeysLazyRoute
  AppAppAdminAdminBackupLazyRoute: typeof AppAppAdminAdminBackupLazyRoute
  AppAppAdminAdminDocsLazyLazyRoute: typeof AppAppAdminAdminDocsLazyLazyRoute
  AppAppAdminAdminConfigurationRoute: typeof AppAppAdminAdminConfigurationRouteWithChildren
  AppAppAdminAdminSettingsRoute: typeof AppAppAdminAdminSettingsRouteWithChildren
  AppAppAdminAdminServersDbIndexRoute: typeof AppAppAdminAdminServersDbIndexRoute
}

const AppAppAdminAdminRouteChildren: AppAppAdminAdminRouteChildren = {
  AppAppAdminAdminActivityMonitorLazyRoute:
    AppAppAdminAdminActivityMonitorLazyRoute,
  AppAppAdminAdminApiKeysLazyRoute: AppAppAdminAdminApiKeysLazyRoute,
  AppAppAdminAdminBackupLazyRoute: AppAppAdminAdminBackupLazyRoute,
  AppAppAdminAdminDocsLazyLazyRoute: AppAppAdminAdminDocsLazyLazyRoute,
  AppAppAdminAdminConfigurationRoute:
    AppAppAdminAdminConfigurationRouteWithChildren,
  AppAppAdminAdminSettingsRoute: AppAppAdminAdminSettingsRouteWithChildren,
  AppAppAdminAdminServersDbIndexRoute: AppAppAdminAdminServersDbIndexRoute,
}

const AppAppAdminAdminRouteWithChildren =
  AppAppAdminAdminRoute._addFileChildren(AppAppAdminAdminRouteChildren)

interface AppAppAdminRouteChildren {
  AppAppAdminAdminRoute: typeof AppAppAdminAdminRouteWithChildren
}

const AppAppAdminRouteChildren: AppAppAdminRouteChildren = {
  AppAppAdminAdminRoute: AppAppAdminAdminRouteWithChildren,
}

const AppAppAdminRouteWithChildren = AppAppAdminRoute._addFileChildren(
  AppAppAdminRouteChildren,
)

interface AppAppDevelopmentDevelopmentRouteChildren {
  AppAppDevelopmentDevelopmentRepositoriesLazyRoute: typeof AppAppDevelopmentDevelopmentRepositoriesLazyRoute
  AppAppDevelopmentDevelopmentTerminalLazyRoute: typeof AppAppDevelopmentDevelopmentTerminalLazyRoute
  AppAppDevelopmentDevelopmentTicketsLazyRoute: typeof AppAppDevelopmentDevelopmentTicketsLazyRoute
  AppAppDevelopmentDevelopmentToolkitLazyRoute: typeof AppAppDevelopmentDevelopmentToolkitLazyRoute
}

const AppAppDevelopmentDevelopmentRouteChildren: AppAppDevelopmentDevelopmentRouteChildren =
  {
    AppAppDevelopmentDevelopmentRepositoriesLazyRoute:
      AppAppDevelopmentDevelopmentRepositoriesLazyRoute,
    AppAppDevelopmentDevelopmentTerminalLazyRoute:
      AppAppDevelopmentDevelopmentTerminalLazyRoute,
    AppAppDevelopmentDevelopmentTicketsLazyRoute:
      AppAppDevelopmentDevelopmentTicketsLazyRoute,
    AppAppDevelopmentDevelopmentToolkitLazyRoute:
      AppAppDevelopmentDevelopmentToolkitLazyRoute,
  }

const AppAppDevelopmentDevelopmentRouteWithChildren =
  AppAppDevelopmentDevelopmentRoute._addFileChildren(
    AppAppDevelopmentDevelopmentRouteChildren,
  )

interface AppAppDevelopmentRouteChildren {
  AppAppDevelopmentDevelopmentRoute: typeof AppAppDevelopmentDevelopmentRouteWithChildren
}

const AppAppDevelopmentRouteChildren: AppAppDevelopmentRouteChildren = {
  AppAppDevelopmentDevelopmentRoute:
    AppAppDevelopmentDevelopmentRouteWithChildren,
}

const AppAppDevelopmentRouteWithChildren =
  AppAppDevelopmentRoute._addFileChildren(AppAppDevelopmentRouteChildren)

interface AppAppHrHrRouteChildren {
  AppAppHrHrAttendanceLazyRoute: typeof AppAppHrHrAttendanceLazyRoute
  AppAppHrHrCalendarLazyRoute: typeof AppAppHrHrCalendarLazyRoute
  AppAppHrHrEmployeesLazyRoute: typeof AppAppHrHrEmployeesLazyRoute
  AppAppHrHrLeaveManagementLazyRoute: typeof AppAppHrHrLeaveManagementLazyRoute
  AppAppHrHrManageRequestsLazyRoute: typeof AppAppHrHrManageRequestsLazyRoute
  AppAppHrHrNotesLazyRoute: typeof AppAppHrHrNotesLazyRoute
}

const AppAppHrHrRouteChildren: AppAppHrHrRouteChildren = {
  AppAppHrHrAttendanceLazyRoute: AppAppHrHrAttendanceLazyRoute,
  AppAppHrHrCalendarLazyRoute: AppAppHrHrCalendarLazyRoute,
  AppAppHrHrEmployeesLazyRoute: AppAppHrHrEmployeesLazyRoute,
  AppAppHrHrLeaveManagementLazyRoute: AppAppHrHrLeaveManagementLazyRoute,
  AppAppHrHrManageRequestsLazyRoute: AppAppHrHrManageRequestsLazyRoute,
  AppAppHrHrNotesLazyRoute: AppAppHrHrNotesLazyRoute,
}

const AppAppHrHrRouteWithChildren = AppAppHrHrRoute._addFileChildren(
  AppAppHrHrRouteChildren,
)

interface AppAppHrRouteChildren {
  AppAppHrHrRoute: typeof AppAppHrHrRouteWithChildren
}

const AppAppHrRouteChildren: AppAppHrRouteChildren = {
  AppAppHrHrRoute: AppAppHrHrRouteWithChildren,
}

const AppAppHrRouteWithChildren = AppAppHrRoute._addFileChildren(
  AppAppHrRouteChildren,
)

interface AppAppManagerManagerRouteChildren {
  AppAppManagerManagerTrackingIndexRoute: typeof AppAppManagerManagerTrackingIndexRoute
}

const AppAppManagerManagerRouteChildren: AppAppManagerManagerRouteChildren = {
  AppAppManagerManagerTrackingIndexRoute:
    AppAppManagerManagerTrackingIndexRoute,
}

const AppAppManagerManagerRouteWithChildren =
  AppAppManagerManagerRoute._addFileChildren(AppAppManagerManagerRouteChildren)

interface AppAppManagerRouteChildren {
  AppAppManagerManagerRoute: typeof AppAppManagerManagerRouteWithChildren
}

const AppAppManagerRouteChildren: AppAppManagerRouteChildren = {
  AppAppManagerManagerRoute: AppAppManagerManagerRouteWithChildren,
}

const AppAppManagerRouteWithChildren = AppAppManagerRoute._addFileChildren(
  AppAppManagerRouteChildren,
)

interface AppAppRouteChildren {
  AppAppTestRoute: typeof AppAppTestRoute
  AppAppAnnouncementsLazyRoute: typeof AppAppAnnouncementsLazyRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppAccountRoute: typeof AppAppAccountRouteWithChildren
  AppAppAdminRoute: typeof AppAppAdminRouteWithChildren
  AppAppDevelopmentRoute: typeof AppAppDevelopmentRouteWithChildren
  AppAppHrRoute: typeof AppAppHrRouteWithChildren
  AppAppManagerRoute: typeof AppAppManagerRouteWithChildren
  AppAppChatsIndexLazyRoute: typeof AppAppChatsIndexLazyRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppTestRoute: AppAppTestRoute,
  AppAppAnnouncementsLazyRoute: AppAppAnnouncementsLazyRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppAccountRoute: AppAppAccountRouteWithChildren,
  AppAppAdminRoute: AppAppAdminRouteWithChildren,
  AppAppDevelopmentRoute: AppAppDevelopmentRouteWithChildren,
  AppAppHrRoute: AppAppHrRouteWithChildren,
  AppAppManagerRoute: AppAppManagerRouteWithChildren,
  AppAppChatsIndexLazyRoute: AppAppChatsIndexLazyRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
